# Generated by Django 3.1.4 on 2021-01-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=254)),
                ('tournament', models.CharField(max_length=254)),
                ('match', models.CharField(max_length=254)),
                ('hour', models.CharField(max_length=60)),
                ('tv', models.CharField(max_length=60)),
            ],
        ),
    ]
